export const inputsByDivision = {
	RED: [
		{
			name: "applicantName",
			label: "Applicant's full/last name",
			type: "text",
			formats: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"],
		},
		{
			name: "applicantGender",
			label: "Applicant's gender",
			type: "select",
			options: [
				{ value: "male", label: "Male" },
				{ value: "female", label: "Female" },
			],
			formats: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
		},
		{
			name: "date",
			label: "Email Date",
			type: "date",
			formats: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
		},
		{
			name: "interviewDate",
			label: "Interview date",
			type: "date",
			formats: ["9", "13"],
		},
		{
			name: "reasons",
			label: "Reason(s)",
			type: "text",
			formats: ["4", "6"],
		},
		{ name: "appLink", label: "Application Link", type: "text", formats: ["13"] },
		{
			name: "firstImpression",
			label: "How was your first impression of the applicant, were they friendly with you, introduced themselves, etc?",
			type: "textarea",
			formats: ["13"],
		},
		{
			name: "answeredTruthfully",
			label: "Did the applicant answer all questions truthfully, provide their full ID, and were they compliant during their search? Did they bring something to the interview they are not supposed to, a firearm for an example?",
			type: "textarea",
			formats: ["13"],
		},
		{
			name: "situationalQuestions",
			label: "How did the applicant respond to the situational questions? Did they have common sense when it came to answering the questions? Do you think they will be a good fit for the department?\n",
			type: "textarea",
			formats: ["13"],
		},
		{
			name: "greatestWeakness",
			label: "What's the Applicant's greatest weakness ( Please be specific )",
			type: "textarea",
			formats: ["13"],
		},
		{
			name: "obstacleCourseProblems",
			label: "Did the applicant have any problems with the physical obstacle course?",
			type: "textarea",
			formats: ["13"],
		},
		{
			name: "acceptedIntoAcademy",
			label: "Do you believe this applicant should be accepted into the academy?",
			type: "textarea",
			formats: ["13"],
		},
		{
			name: "oocQuestions",
			label: "(( Did they answer all OOC questions correctly, were they familiar with the server rules? ))",
			type: "textarea",
			formats: ["13"],
		},
		{
			name: "usageOfMeAndDo",
			label: "(( Do you think they have provided sufficient details and fair usage of /me's and /do's? ))",
			type: "textarea",
			formats: ["13"],
		},
		{
			name: "characterDevelopment",
			label: "(( Did they role-play any 'character development' during the role-play test? E.g. role-playing fatigue/exhaustion, pain etc. ))",
			type: "textarea",
			formats: ["13"],
		},
		{
			name: "workingMicrophone",
			label: "(( Does the player have a working microphone? ))",
			type: "textarea",
			formats: ["13"],
		},
		{
			name: "playerAge",
			label: "(( Is the player 16 or older? ))",
			type: "textarea",
			formats: ["13"],
		},
		{
			name: "speakingEnglish",
			label: "(( Was the applicant proficient at speaking English? ))",
			type: "textarea",
			formats: ["13"],
		},
		{
			name: "rolePlayScreenShots",
			label: "(( Provide screenshots of ALL of their RP throughout the physical evaluation ))",
			hint: "Add link(s) with ; separator. you can also add one link without ; separator. (Also make sure to use the direct link, not the viewer link. https://ibb.co/2223C4VcBF - incorrect / https://i.ibb.co/322jZ6SHT/2025-11-01-22-53.png - correct )",
			type: "textarea",
			formats: ["13"],
		},
		{
			name: "generalFeeling",
			label: "(( How was your general feeling towards them? Do they come across as willing to learn and invest time into this faction, or do they seem like they want to rush and can't dedicate themselves to something long-term? ))\n",
			type: "textarea",
			formats: ["13"],
		},
	],
	TSD: [
		{
			name: "deputyName",
			label: "Deputy Fname and Lname",
			type: "text",
			formats: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
		},
		{
			name: "date",
			label: "Email Date",
			type: "date",
			formats: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
		},
	],
	ATD: [
		{
			name: "deputyName",
			label: "Deputy Fname and Lname",
			type: "text",
			formats: [
				"2",
				"4",
				"6",
				"8",
				"10",
				"12",
				"14",
				"16",
				"18",
				"20",
				"22",
				"24",
				"26",
				"28",
				"30",
				"32",
				"34",
				"36",
				"38",
				"40",
				"41",
				"42",
				"43",
				"44",
				"45",
				"46",
			],
		},
		{
			name: "deputyRank",
			label: "Deputy Rank",
			type: "text",
			formats: [
				"2",
				"4",
				"6",
				"8",
				"10",
				"12",
				"14",
				"16",
				"18",
				"20",
				"22",
				"24",
				"26",
				"28",
				"30",
				"32",
				"34",
				"36",
				"38",
				"40",
				"41",
				"42",
				"43",
				"44",
				"45",
			],
		},
		{
			name: "certificationType",
			label: "Firearm Certification Type",
			type: "text",
			formats: ["41", "42", "43", "44", "46", "47"],
		},
		{
			name: "scoredPoint",
			label: "Deputy Score",
			type: "number",
			formats: ["42"],
		},
		{
			name: "leastPoint",
			label: "Minimum Score",
			type: "number",
			formats: ["42"],
		},
		{
			name: "reasons",
			label: "Reason(s)",
			type: "text",
			formats: ["43", "45"],
		},
		{
			name: "date",
			label: "Email Date",
			type: "date",
			formats: [
				"2",
				"4",
				"6",
				"8",
				"10",
				"12",
				"14",
				"16",
				"18",
				"20",
				"22",
				"24",
				"26",
				"28",
				"30",
				"32",
				"34",
				"36",
				"38",
				"40",
				"46",
				"47",
			],
		},
		{
			name: "issuedBy",
			label: "Issued By",
			type: "text",
			formats: ["47"],
		},
		{
			name: "certificationStatus",
			label: "Certification Status",
			type: "select",
			options: [
				{ value: "acquired", label: "Acquired" },
				{ value: "suspended", label: "Suspended" },
			],
			formats: ["47"],
		},
	],
};
