import type { divisionsType } from "@/types";

/**
 * The category each built-in format is grouped under in its division's picker.
 * Every division keeps its own set of names, and the same id can sit under
 * different headings from one division to the next.
 *
 * Formats without an entry fall back to a single heading for the whole division,
 * and `/admin` can rename, move or clear any of these per format.
 */
export const formatCategories: Partial<Record<divisionsType, Record<string, string>>> = {
	RED: {
		"1": "Applications",
		"2": "Applications",
		"3": "Applications",
		"4": "Applications",
		"5": "Applications",
		"6": "Applications",
		"7": "Interviews",
		"8": "Interviews",
		"9": "Interviews",
		"13": "Interviews",
		"10": "Academy",
		"11": "Academy",
		"12": "Correspondence",
		"14": "Correspondence",
	},
	TSD: {
		"1": "BRAVO Certification",
		"2": "BRAVO Certification",
		"3": "BRAVO Certification",
		"4": "BRAVO Certification",
		"5": "Interceptor Certification",
		"6": "Interceptor Certification",
		"7": "Interceptor Certification",
		"8": "Interceptor Certification",
		"9": "D10 Certification",
		"10": "D10 Certification",
		"11": "D10 Certification",
		"12": "D10 Certification",
	},
	ATD: {
		"1": "Spike Strip Certification",
		"2": "Spike Strip Certification",
		"3": "Spike Strip Certification",
		"4": "Spike Strip Certification",
		"5": "Spike Strip Certification",
		"6": "Spike Strip Certification",
		"7": "Spike Strip Certification",
		"8": "Spike Strip Certification",
		"9": "HIOU Certification",
		"10": "HIOU Certification",
		"11": "HIOU Certification",
		"12": "HIOU Certification",
		"13": "HIOU Certification",
		"14": "HIOU Certification",
		"15": "HIOU Certification",
		"16": "HIOU Certification",
		"17": "HSIU Certification",
		"18": "HSIU Certification",
		"19": "HSIU Certification",
		"20": "HSIU Certification",
		"21": "HSIU Certification",
		"22": "HSIU Certification",
		"23": "HSIU Certification",
		"24": "HSIU Certification",
		"25": "HIU Certification",
		"26": "HIU Certification",
		"27": "HIU Certification",
		"28": "HIU Certification",
		"29": "HIU Certification",
		"30": "HIU Certification",
		"31": "HIU Certification",
		"32": "HIU Certification",
		"33": "HSMU Certification",
		"34": "HSMU Certification",
		"35": "HSMU Certification",
		"36": "HSMU Certification",
		"37": "HSMU Certification",
		"38": "HSMU Certification",
		"39": "HSMU Certification",
		"40": "HSMU Certification",
		"41": "Firearm Certification",
		"42": "Firearm Certification",
		"43": "Firearm Certification",
		"44": "Firearm Certification",
		"45": "Firearm Certification",
		"46": "Personnel Files",
		"47": "Personnel Files",
	},
	FTB: {
		"1": "Training sessions",
		"2": "Training sessions",
		"3": "Training sessions",
		"4": "Evaluations",
		"5": "Evaluations",
		"6": "Pursuits",
		"7": "Reinstatement",
		"8": "Reinstatement",
	},
	SEB: {
		"1": "Correspondence",
		"29": "Correspondence",
		"35": "Correspondence",
		"36": "Correspondence",
		"2": "Logs",
		"3": "Logs",
		"4": "Written exams",
		"5": "Written exams",
		"6": "Written exams",
		"7": "Written exams",
		"8": "Written exams",
		"9": "Written exams",
		"10": "Written exams",
		"11": "Written exams",
		"12": "Written exams",
		"13": "Written exams",
		"14": "Practical exams",
		"15": "Practical exams",
		"16": "Practical exams",
		"17": "Practical exams",
		"18": "Practical exams",
		"19": "Practical exams",
		"20": "Practical exams",
		"21": "Practical exams",
		"22": "Practical exams",
		"23": "Practical exams",
		"24": "Operator exams",
		"25": "Operator exams",
		"34": "Operator exams",
		"26": "Personnel",
		"28": "Personnel",
		"30": "Operator profile",
		"27": "Training",
		"31": "Training",
		"32": "Training",
		"33": "Training",
	},
	General: {
		"1": "Correspondence",
	},
	Supervisory: {
		"1": "Personnel changes",
		"2": "Personnel changes",
		"3": "Personnel changes",
		"6": "Personnel changes",
		"7": "Personnel changes",
		"8": "Personnel changes",
		"10": "Personnel changes",
		"4": "Discharges",
		"11": "Discharges",
		"12": "Discharges",
		"13": "Discharges",
		"5": "Suspensions",
		"17": "Suspensions",
		"9": "Notices",
		"14": "Notices",
		"15": "Notices",
		"16": "Notices",
		"18": "Responses",
		"19": "Responses",
	},
};
